#!/usr/bin/bash
# this file will be executed on the first boot of the system
# run post install hooks
echo first-boot: running post install hooks
mkdir -p /var/log
xbps-reconfigure -a > /var/log/first_install_reconfigure.log

# all done
touch /var/lib/.first_boot_done

echo first-boot: syncing disks
sync
