#!/usr/bin/bash
mkdir -p /dev
mount /dev devfs
chmod 0755 /dev

mkdir -p /dev/shm
mount /dev/shm tmpfs
chmod 1777 /dev/shm

mkdir -p /tmp
mount /tmp tmpfs
chmod 1777 /tmp

chmod 0755 /dev/pts

# required to be owned by root and sticky for rootless Xorg.
mkdir -p /tmp/.X11-unix
chmod 1777 /tmp/.X11-unix
